//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     코드가 다시 생성되었습니다. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemoEngine.Account {
    
    
    public partial class Login {
        
        /// <summary>
        /// ErrorMessage 컨트롤입니다.
        /// </summary>
        /// <remarks>
        /// 자동 생성된 필드입니다.
        /// 수정하려면 디자이너 파일에서 코드 숨김 파일로 필드 선언을 이동합니다.
        /// </remarks>
        protected global::System.Web.UI.WebControls.PlaceHolder ErrorMessage;
        
        /// <summary>
        /// FailureText 컨트롤입니다.
        /// </summary>
        /// <remarks>
        /// 자동 생성된 필드입니다.
        /// 수정하려면 디자이너 파일에서 코드 숨김 파일로 필드 선언을 이동합니다.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal FailureText;
        
        /// <summary>
        /// Email 컨트롤입니다.
        /// </summary>
        /// <remarks>
        /// 자동 생성된 필드입니다.
        /// 수정하려면 디자이너 파일에서 코드 숨김 파일로 필드 선언을 이동합니다.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Email;
        
        /// <summary>
        /// Password 컨트롤입니다.
        /// </summary>
        /// <remarks>
        /// 자동 생성된 필드입니다.
        /// 수정하려면 디자이너 파일에서 코드 숨김 파일로 필드 선언을 이동합니다.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox Password;
        
        /// <summary>
        /// RememberMe 컨트롤입니다.
        /// </summary>
        /// <remarks>
        /// 자동 생성된 필드입니다.
        /// 수정하려면 디자이너 파일에서 코드 숨김 파일로 필드 선언을 이동합니다.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox RememberMe;
        
        /// <summary>
        /// RegisterHyperLink 컨트롤입니다.
        /// </summary>
        /// <remarks>
        /// 자동 생성된 필드입니다.
        /// 수정하려면 디자이너 파일에서 코드 숨김 파일로 필드 선언을 이동합니다.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink RegisterHyperLink;
        
        /// <summary>
        /// OpenAuthLogin 컨트롤입니다.
        /// </summary>
        /// <remarks>
        /// 자동 생성된 필드입니다.
        /// 수정하려면 디자이너 파일에서 코드 숨김 파일로 필드 선언을 이동합니다.
        /// </remarks>
        protected global::MemoEngine.Account.OpenAuthProviders OpenAuthLogin;
    }
}
